# Generated by Django 3.2.8 on 2022-01-09 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('district', models.CharField(max_length=100, null=True)),
                ('pin', models.CharField(max_length=100, null=True)),
                ('bname', models.CharField(max_length=100, null=True)),
                ('accno', models.CharField(max_length=100, null=True)),
                ('ifsc', models.CharField(max_length=100, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='aloki1.PNG', null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Farmerkit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('price', models.FloatField(max_length=100, null=True)),
                ('desc', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('in stock', 'In Stock'), ('out of stock', 'Out Of Stock')], max_length=20, null=True)),
                ('image', models.ImageField(blank=True, default='aloki1.PNG', null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('district', models.CharField(max_length=100, null=True)),
                ('pin', models.CharField(max_length=100, null=True)),
                ('bname', models.CharField(max_length=100, null=True)),
                ('accno', models.CharField(max_length=100, null=True)),
                ('ifsc', models.CharField(max_length=100, null=True)),
                ('dob', models.DateField(null=True)),
                ('exsalary', models.CharField(max_length=10, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='aloki1.PNG', null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Farmermarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('price', models.FloatField(max_length=100, null=True)),
                ('desc', models.CharField(max_length=100, null=True)),
                ('quantity', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('in stock', 'In Stock'), ('out of stock', 'Out Of Stock')], max_length=20, null=True)),
                ('image', models.ImageField(blank=True, default='aloki1.PNG', null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('sname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agriman.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('district', models.CharField(max_length=100, null=True)),
                ('pin', models.CharField(max_length=100, null=True)),
                ('bname', models.CharField(max_length=100, null=True)),
                ('accno', models.CharField(max_length=100, null=True)),
                ('ifsc', models.CharField(max_length=100, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='aloki1.PNG', null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
