# Generated by Django 3.2.8 on 2022-01-10 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agriman', '0002_auto_20220110_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmermarket',
            name='sname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agriman.person'),
        ),
    ]
