# Generated by Django 3.2.8 on 2022-01-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriman', '0003_alter_farmermarket_sname'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('hired', 'hired')], max_length=20, null=True),
        ),
    ]
