# Generated by Django 3.2.8 on 2022-01-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriman', '0004_worker_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmermarket',
            name='CAT',
            field=models.CharField(choices=[('vegetable', 'vegetable'), ('fruits', 'fruits'), ('crops', 'crops')], max_length=20, null=True),
        ),
    ]
